const allQuestions = {
  HTML: [
    { question: "What does HTML stand for?", answers: ["Hyper Text Markup Language", "Home Tool Markup Language", "Hyperlinks and Text Markup Language", "Hyperlinking Text Mark Language"], correct: 0 },
    { question: "Which HTML tag is used to define an internal style sheet?", answers: ["<style>", "<css>", "<script>", "<link>"], correct: 0 },
    { question: "Which tag is used to create a line break in HTML?", answers: ["<br>", "<lb>", "<break>", "<newline>"], correct: 0 },
    { question: "What is the correct HTML element for inserting a horizontal line?", answers: ["<hr>", "<line>", "<break>", "<hl>"], correct: 0 },
    { question: "How can you make a numbered list in HTML?", answers: ["<ol>", "<ul>", "<list>", "<dl>"], correct: 0 },
    { question: "What is the correct HTML element for the largest heading?", answers: ["<h1>", "<heading>", "<head>", "<h6>"], correct: 0 },
    { question: "What is the correct HTML element to define important text?", answers: ["<strong>", "<b>", "<important>", "<i>"], correct: 0 },
    { question: "How can you open a link in a new tab/browser window?", answers: ['<a href="url" target="_blank">', '<a href="url" new>', '<a href="url" target="new">', '<a href="url" blank>'], correct: 0 },
    { question: "Which character is used to indicate an end tag?", answers: ["/", "*", "<", "^"], correct: 0 },
    { question: "How can you make a bulleted list in HTML?", answers: ["<ul>", "<ol>", "<dl>", "<list>"], correct: 0 },
    { question: "What is the correct HTML element to define emphasized text?", answers: ["<em>", "<i>", "<italic>", "<stress>"], correct: 0 },
    { question: "Which HTML attribute specifies an alternate text for an image?", answers: ["alt", "src", "title", "longdesc"], correct: 0 },
    { question: "In HTML, which attribute is used to specify that an input field must be filled out?", answers: ["required", "validate", "placeholder", "formvalidate"], correct: 0 },
    { question: "Which HTML tag is used to display a picture on a webpage?", answers: ["<img>", "<image>", "<pic>", "<src>"], correct: 0 },
    { question: "How do you create a checkbox in HTML?", answers: ['<input type="checkbox">', '<checkbox>', '<input type="check">', '<check>'], correct: 0 },
    { question: "What is the correct way to create a radio button in HTML?", answers: ['<input type="radio">', '<radio>', '<input type="button">', '<button>'], correct: 0 },
    { question: "Which attribute is used to specify the URL of a link?", answers: ["href", "src", "link", "url"], correct: 0 },
    { question: "Which element is used to define the title of a document?", answers: ["<title>", "<head>", "<meta>", "<header>"], correct: 0 },
    { question: "How can you insert a comment in HTML?", answers: ["<!-- comment -->", "// comment", "' comment", "** comment"], correct: 0 },
    { question: "Which tag is used for inserting a video in HTML5?", answers: ["<video>", "<media>", "<movie>", "<film>"], correct: 0 },
    { question: "What does the <a> tag define?", answers: ["A hyperlink", "A paragraph", "An image", "A line break"], correct: 0 },
    { question: "Which tag is used to create a table row?", answers: ["<tr>", "<td>", "<table>", "<th>"], correct: 0 },
    { question: "Which tag defines a table header?", answers: ["<th>", "<td>", "<tr>", "<table>"], correct: 0 },
    { question: "What attribute is used to specify the width of an image?", answers: ["width", "size", "length", "height"], correct: 0 },
    { question: "Which tag is used to group multiple elements?", answers: ["<div>", "<span>", "<section>", "<article>"], correct: 0 },
    { question: "How do you insert a line break without starting a new paragraph?", answers: ["<br>", "<p>", "<lb>", "<break>"], correct: 0 },
    { question: "Which tag is used to define a list item?", answers: ["<li>", "<ul>", "<ol>", "<list>"], correct: 0 },
    { question: "What is the correct element for inserting a horizontal rule?", answers: ["<hr>", "<line>", "<break>", "<rule>"], correct: 0 },
    { question: "Which attribute specifies the language of the document?", answers: ["lang", "xml:lang", "language", "doclang"], correct: 0 },
    { question: "Which HTML element is used for the footer?", answers: ["<footer>", "<bottom>", "<section>", "<aside>"], correct: 0 },
    { question: "How do you create a hyperlink in HTML?", answers: ['<a href="url">', '<link href="url">', '<hyperlink>', '<url>'], correct: 0 },
    { question: "Which tag defines a paragraph?", answers: ["<p>", "<para>", "<text>", "<paragraph>"], correct: 0 },
    { question: "What is the purpose of the alt attribute on an <img> tag?", answers: ["Provide alternative text for the image", "Set image alignment", "Set image source", "Add a caption"], correct: 0 },
    { question: "Which tag is used for the largest heading?", answers: ["<h1>", "<head>", "<h6>", "<heading>"], correct: 0 },
    { question: "What is the default display value of the <span> element?", answers: ["inline", "block", "inline-block", "none"], correct: 0 },
    { question: "Which tag is used to create a drop-down list?", answers: ["<select>", "<dropdown>", "<list>", "<option>"], correct: 0 },
    { question: "Which tag is used to define the body of the HTML document?", answers: ["<body>", "<html>", "<head>", "<section>"], correct: 0 },
    { question: "How do you add a background color in HTML?", answers: ['Using style="background-color: color;"', 'Using <bgcolor>', 'Using <background>', 'Using <color>'], correct: 0 },
    { question: "Which tag defines a section in a document?", answers: ["<section>", "<div>", "<article>", "<span>"], correct: 0 },
    { question: "How do you create an ordered list in HTML?", answers: ["<ol>", "<ul>", "<list>", "<dl>"], correct: 0 },
    { question: "What tag is used to display preformatted text?", answers: ["<pre>", "<code>", "<text>", "<format>"], correct: 0 },
    { question: "Which element is used to specify metadata about an HTML document?", answers: ["<meta>", "<head>", "<title>", "<link>"], correct: 0 },
    { question: "What is the correct HTML for adding a background image?", answers: ['<body style="background-image:url(image.jpg)">', '<background img="image.jpg">', '<img background="image.jpg">', '<body background="image.jpg">'], correct: 0 },
    { question: "Which tag is used to embed an external frame into an HTML document?", answers: ["<iframe>", "<frame>", "<frameset>", "<embed>"], correct: 0 },
    { question: "Which HTML attribute specifies the character encoding for the document?", answers: ["charset", "encoding", "code", "char"], correct: 0 },
    { question: "What is the purpose of the <head> tag?", answers: ["To contain meta-information about the document", "To display the page title", "To define the body content", "To link CSS files"], correct: 0 },
    { question: "How do you make a text bold in HTML?", answers: ["<b>", "<strong>", "<bold>", "<em>"], correct: 0 },
    { question: "What tag is used for a clickable button?", answers: ["<button>", "<input type='button'>", "<a>", "<click>"], correct: 0 },
    { question: "How do you create a text input field?", answers: ['<input type="text">', '<textfield>', '<textinput>', '<input>'], correct: 0 },
    { question: "Which tag is used to define an unordered list?", answers: ["<ul>", "<ol>", "<li>", "<list>"], correct: 0 }
  ],

  // Add similarly for CSS, JavaScript, React, Git, General Knowledge categories
  CSS: [
   
  { question: "What does CSS stand for?", answers: ["Cascading Style Sheets", "Colorful Style Sheets", "Creative Style System", "Computer Style Sheets"], correct: 0 },
  { question: "Which HTML tag is used to link an external CSS file?", answers: ["<link>", "<style>", "<css>", "<script>"], correct: 0 },
  { question: "How do you apply a background color in CSS?", answers: ["background-color", "color-background", "bgcolor", "color"], correct: 0 },
  { question: "Which property is used to change the text color?", answers: ["color", "text-color", "font-color", "background-color"], correct: 0 },
  { question: "How do you select an element with id 'header' in CSS?", answers: ["#header", ".header", "header", "*header"], correct: 0 },
  { question: "How do you select elements with the class name 'menu'?", answers: [".menu", "#menu", "menu", "*menu"], correct: 0 },
  { question: "Which property controls the text size?", answers: ["font-size", "text-style", "font-style", "text-size"], correct: 0 },
  { question: "How do you make text bold in CSS?", answers: ["font-weight: bold;", "font-style: bold;", "font-weight: heavy;", "text-style: bold;"], correct: 0 },
  { question: "Which property is used to change the font family?", answers: ["font-family", "font-style", "font-weight", "text-family"], correct: 0 },
  { question: "How do you center-align text?", answers: ["text-align: center;", "align: center;", "center-align: true;", "text-center: yes;"], correct: 0 },
  { question: "What is the default display value of a <div> element?", answers: ["block", "inline", "inline-block", "none"], correct: 0 },
  { question: "Which property adds space inside the border of an element?", answers: ["padding", "margin", "spacing", "border-spacing"], correct: 0 },
  { question: "Which property adds space outside the border of an element?", answers: ["margin", "padding", "border-spacing", "spacing"], correct: 0 },
  { question: "How do you make a list item marker disappear?", answers: ["list-style-type: none;", "list-style: hidden;", "list-type: none;", "list-hide: true;"], correct: 0 },
  { question: "Which property controls the element’s opacity?", answers: ["opacity", "visibility", "transparent", "alpha"], correct: 0 },
  { question: "How do you make a website responsive?", answers: ["Using media queries", "Using fixed widths", "Using inline styles", "Using tables"], correct: 0 },
  { question: "How do you apply styles only to screens smaller than 600px?", answers: ["@media (max-width: 600px) {}", "@media screen and (min-width: 600px) {}", "@media all and (max-height: 600px) {}", "@media only (max-device-width: 600px) {}"], correct: 0 },
  { question: "Which CSS property is used to change the cursor to a pointer on hover?", answers: ["cursor: pointer;", "cursor: hand;", "pointer: true;", "hover-cursor: pointer;"], correct: 0 },
  { question: "How do you add a comment in CSS?", answers: ["/* This is a comment */", "// This is a comment", "<!-- This is a comment -->", "# This is a comment"], correct: 0 },
  { question: "Which property is used to change the background image?", answers: ["background-image", "image-background", "bg-image", "background-src"], correct: 0 },
  { question: "How do you make the text italic?", answers: ["font-style: italic;", "font-variant: italic;", "font-weight: italic;", "text-style: italic;"], correct: 0 },
  { question: "What does the 'float' property do?", answers: ["Positions an element to the left or right", "Changes element opacity", "Controls the z-index", "Sets element display"], correct: 0 },
  { question: "Which property controls the stacking order of elements?", answers: ["z-index", "stack-order", "order", "layer"], correct: 0 },
  { question: "How do you clear floats?", answers: ["clear: both;", "clear: all;", "float: none;", "clear: left;"], correct: 0 },
  { question: "Which value of display makes an element invisible but still takes space?", answers: ["visibility: hidden;", "display: none;", "opacity: 0;", "hidden: true;"], correct: 0 },
  { question: "How do you select all <p> elements inside a <div>?", answers: ["div p", "div.p", "div > p", "p div"], correct: 0 },
  { question: "What is the correct syntax to set the width of an element to 100 pixels?", answers: ["width: 100px;", "width = 100px;", "width: 100;", "width: '100px';"], correct: 0 },
  { question: "Which CSS property is used to control the space between lines of text?", answers: ["line-height", "letter-spacing", "word-spacing", "text-spacing"], correct: 0 },
  { question: "How do you apply a border of 1px solid black to an element?", answers: ["border: 1px solid black;", "border-style: solid 1px black;", "border-width: 1px black;", "border: black 1px solid;"], correct: 0 },
  { question: "What is the CSS property to make corners rounded?", answers: ["border-radius", "corner-radius", "border-round", "radius"], correct: 0 },
  { question: "How do you make text uppercase in CSS?", answers: ["text-transform: uppercase;", "text-case: uppercase;", "transform: uppercase;", "case: upper;"], correct: 0 },
  { question: "Which property controls the size of the font?", answers: ["font-size", "text-size", "font-style", "font-weight"], correct: 0 },
  { question: "What is the difference between 'em' and 'rem' units?", answers: ["'em' is relative to parent font size, 'rem' is relative to root font size", "'em' is fixed, 'rem' is relative", "'em' is relative to viewport, 'rem' is relative to element", "No difference"], correct: 0 },
  { question: "How do you hide an element completely from the page and layout?", answers: ["display: none;", "visibility: hidden;", "opacity: 0;", "hidden: true;"], correct: 0 },
  { question: "Which CSS property specifies how background images are repeated?", answers: ["background-repeat", "background-style", "image-repeat", "repeat-style"], correct: 0 },
  { question: "What does the 'position: absolute;' do?", answers: ["Positions element relative to the nearest positioned ancestor", "Positions element relative to viewport", "Positions element relative to document flow", "Removes element from document"], correct: 0 },
  { question: "What does 'box-sizing: border-box;' do?", answers: ["Includes padding and border in element’s total width and height", "Excludes padding and border", "Sets box shadows", "Controls margin calculation"], correct: 0 },
  { question: "How to make a flex container?", answers: ["display: flex;", "display: block;", "display: inline-flex;", "display: grid;"], correct: 0 },
  { question: "Which CSS property controls the alignment of flex items along the main axis?", answers: ["justify-content", "align-items", "align-content", "flex-direction"], correct: 0 },
  { question: "Which property controls the spacing between flex items?", answers: ["gap", "margin", "padding", "space-between"], correct: 0 },
  { question: "How do you change the font weight to bold?", answers: ["font-weight: bold;", "font-style: bold;", "font-weight: heavy;", "text-weight: bold;"], correct: 0 },
  { question: "How do you add a shadow effect to text?", answers: ["text-shadow", "box-shadow", "shadow-text", "text-glow"], correct: 0 },
  { question: "Which unit is relative to the viewport width?", answers: ["vw", "vh", "em", "%"], correct: 0 },
  { question: "Which property sets the maximum width of an element?", answers: ["max-width", "width", "min-width", "max-size"], correct: 0 },
  { question: "What does the 'overflow: hidden;' property do?", answers: ["Hides content that overflows the container", "Shows scrollbars", "Resizes the container", "Prevents overflow"], correct: 0 },
  { question: "Which pseudo-class applies style when you hover over an element?", answers: [":hover", ":active", ":focus", ":visited"], correct: 0 },
  { question: "Which pseudo-element is used to insert content before an element?", answers: ["::before", "::after", "::first-letter", "::first-line"], correct: 0 },
  { question: "How do you apply styles only when a checkbox is checked?", answers: [":checked", ":selected", ":checked()", ":enable"], correct: 0 },
  { question: "Which property controls the space between letters?", answers: ["letter-spacing", "word-spacing", "text-spacing", "font-spacing"], correct: 0 }
],

  
  JavaScript: [
    
  { question: "Which company developed JavaScript?", answers: ["Netscape", "Microsoft", "Sun Microsystems", "Google"], correct: 0 },
  { question: "Which symbol is used for comments in JavaScript?", answers: ["//", "/* */", "#", "<!-- -->"], correct: 0 },
  { question: "How do you declare a variable in JavaScript?", answers: ["var", "variable", "letvar", "dim"], correct: 0 },
  { question: "Which keyword is used to declare a block-scoped variable?", answers: ["let", "var", "const", "static"], correct: 0 },
  { question: "Which operator is used for strict equality comparison?", answers: ["===", "==", "=", "!="], correct: 0 },
  { question: "How do you write a function in JavaScript?", answers: ["function myFunction() {}", "def myFunction() {}", "function:myFunction()", "func myFunction() {}"], correct: 0 },
  { question: "Which method is used to output text to the console?", answers: ["console.log()", "print()", "echo()", "console.print()"], correct: 0 },
  { question: "How do you create an array in JavaScript?", answers: ["let arr = [];", "let arr = ();", "let arr = {};", "let arr = <>;"], correct: 0 },
  { question: "What is the output of `typeof null`?", answers: ["object", "null", "undefined", "boolean"], correct: 0 },
  { question: "How do you add an element at the end of an array?", answers: ["push()", "pop()", "shift()", "unshift()"], correct: 0 },
  { question: "How do you remove the first element from an array?", answers: ["shift()", "pop()", "push()", "unshift()"], correct: 0 },
  { question: "What keyword is used to stop a loop?", answers: ["break", "stop", "exit", "return"], correct: 0 },
  { question: "How do you write a conditional statement?", answers: ["if (condition) {}", "if condition {}", "if: condition {}", "if then {}"], correct: 0 },
  { question: "Which method converts a JSON string into a JavaScript object?", answers: ["JSON.parse()", "JSON.stringify()", "JSON.convert()", "JSON.objectify()"], correct: 0 },
  { question: "Which method converts a JavaScript object into a JSON string?", answers: ["JSON.stringify()", "JSON.parse()", "JSON.toString()", "JSON.objectify()"], correct: 0 },
  { question: "What is the output of `2 + '2'`?", answers: ["'22'", "4", "NaN", "Error"], correct: 0 },
  { question: "Which keyword declares a constant variable?", answers: ["const", "let", "var", "constant"], correct: 0 },
  { question: "What is a closure in JavaScript?", answers: ["A function that remembers the environment in which it was created", "A loop inside another loop", "An object inside a function", "A global variable"], correct: 0 },
  { question: "How do you write an arrow function?", answers: ["() => {}", "function() => {}", "=> function()", "function => ()"], correct: 0 },
  { question: "Which event occurs when a user clicks on an HTML element?", answers: ["click", "hover", "change", "submit"], correct: 0 },
  { question: "How do you add a comment in JavaScript?", answers: ["// This is a comment", "/* This is a comment */", "# This is a comment", "<!-- This is a comment -->"], correct: 0 },
  { question: "What does `NaN` stand for?", answers: ["Not a Number", "Null and None", "No Action Needed", "Number and Null"], correct: 0 },
  { question: "How do you convert a string '123' to a number?", answers: ["Number('123')", "parseInt('123')", "+ '123'", "All of the above"], correct: 3 },
  { question: "Which method adds an element at the beginning of an array?", answers: ["unshift()", "push()", "shift()", "pop()"], correct: 0 },
  { question: "How do you check if a variable is an array?", answers: ["Array.isArray()", "typeof", "isArray()", "arrayCheck()"], correct: 0 },
  { question: "Which of the following is NOT a JavaScript data type?", answers: ["Float", "Number", "String", "Boolean"], correct: 0 },
  { question: "How do you create an object in JavaScript?", answers: ["let obj = {};", "let obj = [];", "let obj = ();", "let obj = <>;"], correct: 0 },
  { question: "How do you access the first element of an array `arr`?", answers: ["arr[0]", "arr.first", "arr(0)", "arr[1]"], correct: 0 },
  { question: "Which keyword is used to handle exceptions?", answers: ["try", "catch", "throw", "finally"], correct: 0 },
  { question: "What does the `===` operator do?", answers: ["Checks value and type equality", "Checks only value equality", "Assigns value", "Compares object references"], correct: 0 },
  { question: "Which method removes the last element from an array?", answers: ["pop()", "push()", "shift()", "unshift()"], correct: 0 },
  { question: "How do you write a for loop in JavaScript?", answers: ["for (let i = 0; i < 10; i++) {}", "for i in range(10) {}", "for (i = 0; i < 10)", "loop for 10 times"], correct: 0 },
  { question: "Which method is used to add an element after a specific element in the DOM?", answers: ["insertAdjacentHTML()", "appendChild()", "insertBefore()", "replaceChild()"], correct: 0 },
  { question: "What is the output of `typeof []`?", answers: ["object", "array", "undefined", "list"], correct: 0 },
  { question: "How do you declare a function expression?", answers: ["const f = function() {}", "function f() {}", "function: f() {}", "func f() {}"], correct: 0 },
  { question: "Which method removes whitespace from both ends of a string?", answers: ["trim()", "strip()", "clean()", "remove()"], correct: 0 },
  { question: "How do you check if a number `x` is NaN?", answers: ["isNaN(x)", "x == NaN", "typeof x == 'NaN'", "x === NaN"], correct: 0 },
  { question: "Which of the following is a primitive data type?", answers: ["string", "object", "array", "function"], correct: 0 },
  { question: "How can you create a date object in JavaScript?", answers: ["new Date()", "Date()", "createDate()", "date()"], correct: 0 },
  { question: "What is event bubbling in JavaScript?", answers: ["Event propagates from child to parent", "Event propagates from parent to child", "Event stops at target", "Event does not propagate"], correct: 0 },
  { question: "How do you declare a default parameter in a function?", answers: ["function f(a = 5) {}", "function f(a: 5) {}", "function f(a ? 5) {}", "function f(a default 5) {}"], correct: 0 },
  { question: "Which of the following creates a new array from calling a function on every element?", answers: ["map()", "forEach()", "filter()", "reduce()"], correct: 0 },
  { question: "How do you check if an object has a specific property?", answers: ["obj.hasOwnProperty('prop')", "'prop' in obj", "obj.propertyExists('prop')", "Both first and second"], correct: 3 },
  { question: "What will be the output of `console.log(0.1 + 0.2 == 0.3)`?", answers: ["false", "true", "undefined", "NaN"], correct: 0 },
  { question: "How can you generate a random number between 0 and 1?", answers: ["Math.random()", "Random()", "Math.rand()", "random()"], correct: 0 },
  { question: "What keyword is used to define an asynchronous function?", answers: ["async", "await", "defer", "setTimeout"], correct: 0 },
  { question: "How do you handle promises in JavaScript?", answers: [".then() and .catch()", "try/catch", "async/await", "All of the above"], correct: 3 },
  { question: "Which method converts a string to lowercase?", answers: ["toLowerCase()", "toLower()", "lowercase()", "downcase()"], correct: 0 },
  { question: "How do you declare a class in JavaScript?", answers: ["class MyClass {}", "function MyClass() {}", "class: MyClass {}", "declare class MyClass {}"], correct: 0 },
  { question: "Which of these is a JavaScript framework?", answers: ["React", "Django", "Laravel", "Ruby on Rails"], correct: 0 }


  ],
  React: [
    // 50 React questions
    
  { question: "Who developed React?", answers: ["Facebook", "Google", "Microsoft", "Apple"], correct: 0 },
  { question: "What is JSX in React?", answers: ["A syntax extension for JavaScript", "A CSS framework", "A database", "A templating engine"], correct: 0 },
  { question: "Which method is used to render React elements into the DOM?", answers: ["ReactDOM.render()", "render()", "React.render()", "DOM.render()"], correct: 0 },
  { question: "What is the purpose of the render() method in a React component?", answers: ["Returns the JSX to be rendered", "Initializes state", "Updates props", "Handles events"], correct: 0 },
  { question: "How do you create a React component using a function?", answers: ["function MyComponent() { return <div>Hello</div>; }", "component MyComponent() {}", "createComponent()", "class MyComponent extends React.Component"], correct: 0 },
  { question: "What is a React Hook?", answers: ["A special function to use React features in functional components", "A CSS styling tool", "A type of component", "A router"], correct: 0 },
  { question: "Which hook is used to manage state in a functional component?", answers: ["useState", "useEffect", "useContext", "useReducer"], correct: 0 },
  { question: "How do you pass data from a parent component to a child component?", answers: ["Using props", "Using state", "Using refs", "Using context"], correct: 0 },
  { question: "Which hook is used for side effects like data fetching?", answers: ["useEffect", "useState", "useCallback", "useMemo"], correct: 0 },
  { question: "What is the purpose of keys in lists in React?", answers: ["To uniquely identify elements", "To style elements", "To bind event handlers", "To set state"], correct: 0 },
  { question: "What is the difference between state and props?", answers: ["State is internal and mutable; props are external and immutable", "State is immutable; props are mutable", "Both are mutable", "Both are immutable"], correct: 0 },
  { question: "What does lifting state up mean in React?", answers: ["Moving state to the nearest common ancestor component", "Passing props down", "Using Redux", "Creating global variables"], correct: 0 },
  { question: "What is a controlled component in React?", answers: ["A form element whose value is controlled by React state", "A component with internal state", "A component using Redux", "A component rendered conditionally"], correct: 0 },
  { question: "Which of these lifecycle methods is called after a component is mounted?", answers: ["componentDidMount", "componentWillMount", "componentDidUpdate", "componentWillUnmount"], correct: 0 },
  { question: "What is a higher-order component (HOC)?", answers: ["A function that takes a component and returns a new component", "A component with higher priority", "A component rendered conditionally", "A component using hooks"], correct: 0 },
  { question: "How do you prevent a default form submission in React?", answers: ["event.preventDefault()", "event.stopPropagation()", "return false", "event.defaultPrevent()"], correct: 0 },
  { question: "What is the virtual DOM?", answers: ["A lightweight JavaScript representation of the real DOM", "A new HTML version", "A DOM extension", "A browser API"], correct: 0 },
  { question: "How can you optimize performance in React?", answers: ["Using React.memo and useMemo", "Using setState frequently", "Avoiding keys in lists", "Using inline functions in render"], correct: 0 },
  { question: "Which package is commonly used for routing in React?", answers: ["react-router-dom", "redux", "axios", "react-redux"], correct: 0 },
  { question: "What does the useContext hook do?", answers: ["Accesses React context values", "Manages local state", "Handles events", "Fetches data"], correct: 0 },
  { question: "What is the purpose of React.Fragment?", answers: ["To group a list of children without adding extra nodes to the DOM", "To style components", "To handle events", "To create portals"], correct: 0 },
  { question: "How do you handle events in React?", answers: ["Using camelCase props, e.g., onClick", "Using lowercase event attributes", "Using addEventListener", "Directly in HTML"], correct: 0 },
  { question: "What is JSX transpiled into?", answers: ["React.createElement calls", "HTML", "JSON", "JavaScript functions"], correct: 0 },
  { question: "How do you conditionally render components in React?", answers: ["Using JavaScript ternary or && operators inside JSX", "Using if statements outside JSX", "Using CSS visibility", "Using inline styles"], correct: 0 },
  { question: "What does React.StrictMode do?", answers: ["Helps find potential problems in an application", "Improves performance", "Enables routing", "Adds styling"], correct: 0 },
  { question: "How do you update state in class components?", answers: ["this.setState()", "this.state = {}", "updateState()", "setState()"], correct: 0 },
  { question: "Which hook is used for memoizing expensive calculations?", answers: ["useMemo", "useCallback", "useEffect", "useState"], correct: 0 },
  { question: "What is prop drilling?", answers: ["Passing props through multiple nested components", "Passing state", "Using Redux", "Using context"], correct: 0 },
  { question: "What is the default behavior of React when a state changes?", answers: ["It re-renders the component", "It reloads the page", "It does nothing", "It re-mounts the component"], correct: 0 },
  { question: "Which of these is NOT a valid way to style React components?", answers: ["Using inline styles", "Using CSS modules", "Using styled-components", "Using SQL"], correct: 3 },
  { question: "What is the purpose of keys in React lists?", answers: ["Helps React identify which items have changed", "Styles the items", "Handles events", "Stores state"], correct: 0 },
  { question: "How do you pass a function as a prop?", answers: ["<Child onClick={handleClick} />", "<Child onClick='handleClick' />", "<Child onClick='handleClick()' />", "<Child onClick={handleClick()} />"], correct: 0 },
  { question: "Which React hook is used to perform side effects in functional components?", answers: ["useEffect", "useState", "useReducer", "useContext"], correct: 0 },
  { question: "What is the role of Redux in a React application?", answers: ["State management", "Routing", "Fetching data", "Styling components"], correct: 0 },
  { question: "How do you create a ref in React?", answers: ["React.createRef()", "useRef()", "createRef()", "Both React.createRef() and useRef()"], correct: 3 },
  { question: "How can you prevent re-rendering of a component when props have not changed?", answers: ["React.memo()", "shouldComponentUpdate()", "PureComponent", "All of the above"], correct: 3 },
  { question: "Which lifecycle method is called before a component unmounts?", answers: ["componentWillUnmount", "componentDidMount", "componentDidUpdate", "render"], correct: 0 },
  { question: "What does the useReducer hook do?", answers: ["Manages complex state logic", "Manages side effects", "Replaces useState", "None of the above"], correct: 0 },
  { question: "How can you share state between components without prop drilling?", answers: ["Using Context API", "Using Redux", "Both Context API and Redux", "Using useState"], correct: 2 },
  { question: "What is React.lazy used for?", answers: ["Code splitting and lazy loading components", "Handling errors", "Managing state", "Routing"], correct: 0 },
  { question: "Which hook lets you cache a function definition to avoid re-creating it?", answers: ["useCallback", "useMemo", "useState", "useEffect"], correct: 0 },
  { question: "How do you create a portal in React?", answers: ["ReactDOM.createPortal()", "React.createPortal()", "createPortal()", "portal()"], correct: 0 },
  { question: "What is the use of useImperativeHandle hook?", answers: ["Customizes the instance value exposed to parent components when using refs", "Manages state", "Handles side effects", "Optimizes performance"], correct: 0 },
  { question: "How do you handle forms in React?", answers: ["Using controlled components", "Using uncontrolled components", "Both controlled and uncontrolled", "Using only vanilla HTML forms"], correct: 2 },
  { question: "What is reconciliation in React?", answers: ["The process React uses to update the DOM efficiently", "Synchronizing state", "Handling events", "Fetching data"], correct: 0 },
  { question: "Which hook would you use to share state logic between components?", answers: ["Custom hooks", "useState", "useEffect", "useContext"], correct: 0 },
  { question: "How do you write a class component in React?", answers: ["class MyComponent extends React.Component {}", "function MyComponent() {}", "component MyComponent {}", "component class MyComponent {}"], correct: 0 },
  { question: "What is the difference between React and ReactDOM?", answers: ["React is for building components, ReactDOM is for DOM manipulation", "ReactDOM is a library", "React is a framework", "They are the same"], correct: 0 },
  { question: "Which hook is used to get the previous props or state?", answers: ["useRef", "useEffect", "useMemo", "useCallback"], correct: 0 },
  { question: "How can you memoize a functional component to prevent unnecessary renders?", answers: ["React.memo()", "useMemo()", "useCallback()", "memoize()"], correct: 0 },
  { question: "What is a pure component?", answers: ["A component that only re-renders when its props or state change", "A component with no side effects", "A functional component", "A component without state"], correct: 0 },
  { question: "How can you pass children elements to a component?", answers: ["Using the children prop", "Using props.children", "Both", "Neither"], correct: 2 }
],


  Git: [
    // 50 Git questions
    
  { question: "What is Git?", answers: ["A version control system", "A programming language", "A database", "An operating system"], correct: 0 },
  { question: "Which command initializes a new Git repository?", answers: ["git init", "git start", "git create", "git new"], correct: 0 },
  { question: "How do you check the status of your Git repository?", answers: ["git status", "git check", "git log", "git info"], correct: 0 },
  { question: "What command stages changes for commit?", answers: ["git add", "git commit", "git stage", "git push"], correct: 0 },
  { question: "Which command commits staged changes?", answers: ["git commit", "git add", "git push", "git save"], correct: 0 },
  { question: "How do you see commit history?", answers: ["git log", "git history", "git commits", "git show"], correct: 0 },
  { question: "What command creates a new branch?", answers: ["git branch branch-name", "git new branch", "git create branch", "git checkout branch-name"], correct: 0 },
  { question: "How do you switch branches?", answers: ["git checkout branch-name", "git switch branch-name", "git change branch", "git branch switch"], correct: 0 },
  { question: "What command merges a branch into the current branch?", answers: ["git merge branch-name", "git combine branch-name", "git join branch-name", "git integrate branch-name"], correct: 0 },
  { question: "How do you clone a remote repository?", answers: ["git clone repo-url", "git copy repo-url", "git download repo-url", "git get repo-url"], correct: 0 },
  { question: "Which command pushes commits to a remote repository?", answers: ["git push", "git upload", "git send", "git deploy"], correct: 0 },
  { question: "How do you pull changes from a remote repository?", answers: ["git pull", "git fetch", "git update", "git merge"], correct: 0 },
  { question: "What is the command to create a .gitignore file?", answers: ["Create a file named .gitignore manually", "git ignore", "git add .gitignore", "git exclude"], correct: 0 },
  { question: "What does the git status command show?", answers: ["Current branch and staged/unstaged changes", "Commit history", "Remote repository info", "File differences"], correct: 0 },
  { question: "How do you undo the last commit but keep the changes staged?", answers: ["git reset --soft HEAD~1", "git reset --hard HEAD~1", "git revert HEAD", "git checkout HEAD~1"], correct: 0 },
  { question: "How to discard changes in a file before staging?", answers: ["git checkout -- filename", "git reset filename", "git clean filename", "git revert filename"], correct: 0 },
  { question: "Which command removes untracked files?", answers: ["git clean -f", "git remove", "git delete", "git prune"], correct: 0 },
  { question: "How do you rename a branch?", answers: ["git branch -m old-name new-name", "git rename branch", "git switch -m new-name", "git move branch"], correct: 0 },
  { question: "What does 'git fetch' do?", answers: ["Downloads remote changes but doesn’t merge", "Downloads and merges remote changes", "Uploads local changes", "Deletes remote branches"], correct: 0 },
  { question: "What is the difference between git pull and git fetch?", answers: ["git pull = fetch + merge; git fetch just downloads", "git pull uploads changes; git fetch downloads", "No difference", "git fetch deletes remote branches"], correct: 0 },
  { question: "How do you create a tag in Git?", answers: ["git tag tagname", "git create tag", "git label tagname", "git mark tagname"], correct: 0 },
  { question: "How to push tags to a remote repository?", answers: ["git push origin --tags", "git push tags", "git push --all-tags", "git push origin tags"], correct: 0 },
  { question: "What command shows differences between working directory and last commit?", answers: ["git diff", "git status", "git log", "git compare"], correct: 0 },
  { question: "How do you undo changes in the staging area?", answers: ["git reset HEAD filename", "git undo filename", "git revert filename", "git checkout filename"], correct: 0 },
  { question: "What does 'git stash' do?", answers: ["Temporarily saves uncommitted changes", "Deletes changes", "Commits changes", "Creates a new branch"], correct: 0 },
  { question: "How to apply stashed changes back to working directory?", answers: ["git stash apply", "git stash pop", "git stash restore", "git stash merge"], correct: 1 },
  { question: "What is a fast-forward merge?", answers: ["A merge where branch pointer moves forward without creating a merge commit", "A merge that creates a new commit", "A merge conflict", "None of the above"], correct: 0 },
  { question: "How do you view the remote repositories linked to your repo?", answers: ["git remote -v", "git remote", "git fetch", "git clone"], correct: 0 },
  { question: "How do you delete a branch locally?", answers: ["git branch -d branch-name", "git delete branch-name", "git remove branch-name", "git branch --delete branch-name"], correct: 0 },
  { question: "How to delete a remote branch?", answers: ["git push origin --delete branch-name", "git delete remote branch-name", "git remove branch branch-name", "git branch -r -d branch-name"], correct: 0 },
  { question: "Which file contains metadata and object database in a Git repo?", answers: [".git directory", "package.json", "README.md", "index.html"], correct: 0 },
  { question: "What is a commit hash?", answers: ["A unique SHA-1 identifier for each commit", "A password", "A tag name", "A branch name"], correct: 0 },
  { question: "What is the use of git cherry-pick?", answers: ["Apply a specific commit from another branch", "Delete a commit", "Create a new commit", "Merge branches"], correct: 0 },
  { question: "How do you revert a commit by creating a new commit?", answers: ["git revert commit-hash", "git reset", "git undo", "git remove"], correct: 0 },
  { question: "What is the purpose of .gitignore file?", answers: ["To specify files and folders Git should ignore", "To track files", "To store commits", "To configure remote"], correct: 0 },
  { question: "What is the difference between git reset --soft and git reset --hard?", answers: ["--soft keeps changes staged; --hard discards all changes", "--soft discards all changes; --hard keeps staged", "No difference", "Both discard changes"], correct: 0 },
  { question: "How do you configure your Git username?", answers: ["git config --global user.name 'Your Name'", "git username set", "git user set", "git config user"], correct: 0 },
  { question: "How to see the difference between two commits?", answers: ["git diff commit1 commit2", "git compare", "git log", "git show"], correct: 0 },
  { question: "What does 'HEAD' refer to in Git?", answers: ["The current commit your repo is on", "The first commit", "The remote branch", "The staging area"], correct: 0 },
  { question: "How do you abort a merge conflict resolution?", answers: ["git merge --abort", "git reset --merge", "git revert", "git abort"], correct: 0 },
  { question: "How do you squash commits in Git?", answers: ["Using interactive rebase git rebase -i", "git squash", "git merge --squash", "git commit --amend"], correct: 0 },
  { question: "What is the default branch name in Git 2.28+?", answers: ["main", "master", "develop", "production"], correct: 0 },
  { question: "How to set up a remote repository?", answers: ["git remote add origin url", "git remote set url", "git add remote", "git init remote"], correct: 0 },
  { question: "Which command lists all branches?", answers: ["git branch", "git list branches", "git show branches", "git branches"], correct: 0 },
  { question: "What command shows changes between staged and committed versions?", answers: ["git diff --staged", "git diff", "git status", "git show"], correct: 0 },
  { question: "How to see changes for a specific file?", answers: ["git diff filename", "git show filename", "git log filename", "git status filename"], correct: 0 },
  { question: "How do you add a commit message?", answers: ["git commit -m 'message'", "git message 'message'", "git add -m 'message'", "git push -m 'message'"], correct: 0 },
  { question: "Which command can be used to edit the last commit message?", answers: ["git commit --amend", "git edit last", "git change message", "git rebase"], correct: 0 },
  { question: "How do you stash only staged changes?", answers: ["git stash push -k", "git stash staged", "git stash --staged", "git stash -s"], correct: 0 },
  { question: "How to create a bare repository?", answers: ["git init --bare", "git bare init", "git create bare", "git init --repo"], correct: 0 }


  ],
  "General Knowledge": [
    // 50 GK questions
    
  { question: "What is the capital of France?", answers: ["Paris", "London", "Berlin", "Madrid"], correct: 0 },
  { question: "Who wrote the play 'Romeo and Juliet'?", answers: ["William Shakespeare", "Charles Dickens", "Leo Tolstoy", "Mark Twain"], correct: 0 },
  { question: "Which planet is known as the Red Planet?", answers: ["Mars", "Jupiter", "Saturn", "Venus"], correct: 0 },
  { question: "What is the largest ocean on Earth?", answers: ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], correct: 0 },
  { question: "Who was the first President of the United States?", answers: ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"], correct: 0 },
  { question: "What is the hardest natural substance on Earth?", answers: ["Diamond", "Gold", "Iron", "Silver"], correct: 0 },
  { question: "Which country is known as the Land of the Rising Sun?", answers: ["Japan", "China", "South Korea", "Thailand"], correct: 0 },
  { question: "In which year did the Titanic sink?", answers: ["1912", "1905", "1920", "1898"], correct: 0 },
  { question: "Who painted the Mona Lisa?", answers: ["Leonardo da Vinci", "Pablo Picasso", "Vincent van Gogh", "Michelangelo"], correct: 0 },
  { question: "What is the chemical symbol for water?", answers: ["H2O", "O2", "CO2", "NaCl"], correct: 0 },
  { question: "Which continent is the Sahara Desert located in?", answers: ["Africa", "Asia", "Australia", "South America"], correct: 0 },
  { question: "Who discovered penicillin?", answers: ["Alexander Fleming", "Marie Curie", "Isaac Newton", "Louis Pasteur"], correct: 0 },
  { question: "What is the currency of Japan?", answers: ["Yen", "Dollar", "Euro", "Peso"], correct: 0 },
  { question: "Which element has the atomic number 1?", answers: ["Hydrogen", "Helium", "Oxygen", "Carbon"], correct: 0 },
  { question: "What is the tallest mountain in the world?", answers: ["Mount Everest", "K2", "Kangchenjunga", "Lhotse"], correct: 0 },
  { question: "Who is known as the father of modern physics?", answers: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Nikola Tesla"], correct: 0 },
  { question: "Which country hosted the 2016 Summer Olympics?", answers: ["Brazil", "China", "United Kingdom", "Russia"], correct: 0 },
  { question: "What is the main language spoken in Brazil?", answers: ["Portuguese", "Spanish", "English", "French"], correct: 0 },
  { question: "Which planet has the most moons?", answers: ["Saturn", "Jupiter", "Mars", "Neptune"], correct: 0 },
  { question: "Who invented the telephone?", answers: ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Guglielmo Marconi"], correct: 0 },
  { question: "What is the smallest country in the world?", answers: ["Vatican City", "Monaco", "San Marino", "Liechtenstein"], correct: 0 },
  { question: "Which organ in the human body is responsible for pumping blood?", answers: ["Heart", "Liver", "Kidney", "Lung"], correct: 0 },
  { question: "In which city is the famous Colosseum located?", answers: ["Rome", "Athens", "Istanbul", "Paris"], correct: 0 },
  { question: "Which gas do plants absorb from the atmosphere?", answers: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Hydrogen"], correct: 0 },
  { question: "Who wrote the novel '1984'?", answers: ["George Orwell", "Aldous Huxley", "J.K. Rowling", "Mark Twain"], correct: 0 },
  { question: "What is the boiling point of water at sea level?", answers: ["100°C", "90°C", "80°C", "70°C"], correct: 0 },
  { question: "Which famous scientist developed the theory of relativity?", answers: ["Albert Einstein", "Isaac Newton", "Stephen Hawking", "Nikola Tesla"], correct: 0 },
  { question: "Which is the longest river in the world?", answers: ["Nile", "Amazon", "Yangtze", "Mississippi"], correct: 0 },
  { question: "What does DNA stand for?", answers: ["Deoxyribonucleic Acid", "Deoxyribogenetic Acid", "Dinucleic Acid", "Dioxyribonucleic Acid"], correct: 0 },
  { question: "Which country gifted the Statue of Liberty to the USA?", answers: ["France", "England", "Germany", "Canada"], correct: 0 },
  { question: "Which instrument measures atmospheric pressure?", answers: ["Barometer", "Thermometer", "Hygrometer", "Anemometer"], correct: 0 },
  { question: "What is the name of the largest reef system in the world?", answers: ["Great Barrier Reef", "Belize Barrier Reef", "Red Sea Coral Reef", "Florida Reef"], correct: 0 },
  { question: "Which metal is liquid at room temperature?", answers: ["Mercury", "Gold", "Silver", "Copper"], correct: 0 },
  { question: "Which planet is closest to the Sun?", answers: ["Mercury", "Venus", "Earth", "Mars"], correct: 0 },
  { question: "Who is the author of 'Harry Potter' series?", answers: ["J.K. Rowling", "J.R.R. Tolkien", "Stephen King", "Suzanne Collins"], correct: 0 },
  { question: "Which country is known as the Land of the Thunder Dragon?", answers: ["Bhutan", "Nepal", "Tibet", "Mongolia"], correct: 0 },
  { question: "Which year did World War II end?", answers: ["1945", "1939", "1918", "1963"], correct: 0 },
  { question: "What is the main ingredient in traditional Japanese sushi?", answers: ["Rice", "Noodles", "Bread", "Potatoes"], correct: 0 },
  { question: "Which scientist is famous for his laws of motion?", answers: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Nikola Tesla"], correct: 0 },
  { question: "What is the largest mammal in the world?", answers: ["Blue Whale", "Elephant", "Giraffe", "Hippopotamus"], correct: 0 },
  { question: "Which city hosted the first modern Olympic Games?", answers: ["Athens", "Paris", "London", "Rome"], correct: 0 },
  { question: "What is the main language spoken in Canada?", answers: ["English and French", "English only", "French only", "Spanish"], correct: 0 },
  { question: "Who invented the light bulb?", answers: ["Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Benjamin Franklin"], correct: 0 },
  { question: "What is the capital of Australia?", answers: ["Canberra", "Sydney", "Melbourne", "Brisbane"], correct: 0 },
  { question: "What is the chemical formula of table salt?", answers: ["NaCl", "KCl", "NaCO3", "CaCl2"], correct: 0 },
  { question: "Who painted the ceiling of the Sistine Chapel?", answers: ["Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"], correct: 0 },
  { question: "What is the fastest land animal?", answers: ["Cheetah", "Lion", "Tiger", "Leopard"], correct: 0 },
  { question: "What is the smallest unit of life?", answers: ["Cell", "Atom", "Molecule", "Organ"], correct: 0 },
  { question: "Which is the largest planet in our Solar System?", answers: ["Jupiter", "Saturn", "Neptune", "Earth"], correct: 0 },
  { question: "Who was known as the Maid of Orleans?", answers: ["Joan of Arc", "Cleopatra", "Queen Elizabeth I", "Marie Curie"], correct: 0 },
  { question: "What is the most abundant gas in Earth's atmosphere?", answers: ["Nitrogen", "Oxygen", "Carbon Dioxide", "Hydrogen"], correct: 0 },
  { question: "Which country invented paper?", answers: ["China", "Egypt", "Greece", "India"], correct: 0 }


  ]
};
